"""Serializers for configurable aggregation endpoints."""

from collections import OrderedDict
from inspect import isclass
from typing import ClassVar

from rest_framework import serializers
from rest_framework.fields import Field
from rest_framework.settings import api_settings

from .enums import AggregationScope


class AggregatingSerializer(serializers.ModelSerializer):
    """
    A serializer that works with :class:`AggregatingViewSet` to provide an
    aggregation endpoint.

    Configure a subclass with these properties:

    * ``Meta.model``: the base model of the endpoint.
    * ``Meta.fields``: public field names the endpoint may return. These may
      map to Django ORM paths through :meth:`field_to_database_path`.
    * ``aggregates``: ``{field_name: aggregate_class_or_expression}`` pairs.
    * ``slice_fields``: ``{slice_name: database_filter_expression}`` pairs.
    * ``field_to_database_path``: maps a public name to its Django ORM path.

    No serializer field attributes are needed: aggregation queries return
    dictionaries and :meth:`to_representation` renders those values directly.
    """

    # Aggregate classes and preconstructed aggregate-containing expressions
    # produce row, selected-slice, and slice-percentage totals. An instance
    # lets a measure use a custom expression such as
    # ``Sum(F("amount") * F("quantity"))``.
    aggregates: ClassVar[dict[str, object]] = {}

    # A slice field ``{"product": "items__product__code__istartswith"}``
    # accepts repeated ``slice_by_product`` URL parameters. Values for one
    # slice are ORed; different configured slices are ANDed.
    slice_fields: ClassVar[dict[str, str]] = {}

    # Dynamic slices on omitted public fields accept only these Django lookup
    # names. Subclasses may replace this set to narrow the public API or allow
    # a project-specific lookup registered on the target field.
    dynamic_slice_lookups: ClassVar[frozenset[str]] = frozenset(
        {
            "exact",
            "iexact",
            "contains",
            "icontains",
            "in",
            "gt",
            "gte",
            "lt",
            "lte",
            "startswith",
            "istartswith",
            "endswith",
            "iendswith",
            "range",
            "date",
            "year",
            "iso_year",
            "month",
            "day",
            "week",
            "week_day",
            "iso_week_day",
            "quarter",
            "time",
            "hour",
            "minute",
            "second",
            "isnull",
            "regex",
            "iregex",
        }
    )

    @staticmethod
    def field_to_database_path(field_name):
        """Map a public field name to its Django ORM path."""
        return field_name

    def get_fields(self):
        """
        Return requested public dimensions in request order.

        ``?fields=`` is a comma-delimited subset of ``Meta.fields`` and
        controls aggregation drill-down. Aggregate fields are generated by the
        viewset and do not need to be requested. Unknown fields are ignored.
        """
        field_list = "request" in self.context and self.context[
            "request"
        ].query_params.get("fields", None)
        if not field_list:
            return {field: Field() for field in self.Meta.fields}

        field_names = field_list.split(",")
        field_names.extend(self.get_ordering_dimension_fields())

        return {field: Field() for field in field_names if field in self.Meta.fields}

    def get_ordering_fields(self):
        """Return the comma-delimited ordering terms without direction markers."""
        return [term.lstrip("-") for term in self.get_ordering_terms()]

    def get_ordering_terms(self):
        """Return the non-empty comma-delimited ordering terms in request order."""
        ordering = self.context["request"].query_params.get(api_settings.ORDERING_PARAM)
        return (
            [term.strip() for term in ordering.split(",") if term.strip()]
            if ordering
            else []
        )

    def get_ordering_dimension_fields(self):
        """Return public dimensions needed to support explicit ordering."""
        dimensions = []
        for ordering_field in self.get_ordering_fields():
            if ordering_field in self.Meta.fields:
                dimensions.append(ordering_field)
                continue

            dimensions.extend(
                field_name
                for field_name in self.Meta.fields
                if self.field_to_database_path(field_name) == ordering_field
            )
        return dimensions

    def get_aggregate_field_names(self):
        """Return generated aggregate names in response order."""
        aggregate_fields = []
        for field_name, aggregate in self.aggregates.items():
            aggregate_fields.append(
                self.get_aggregate_field_name(
                    field_name, aggregate, AggregationScope.ROW
                )
            )
            aggregate_fields.extend(
                [
                    self.get_aggregate_field_name(
                        field_name, aggregate, AggregationScope.SLICE
                    ),
                    self.get_aggregate_field_name(
                        field_name,
                        aggregate,
                        AggregationScope.SLICE,
                        AggregationScope.ROW,
                    ),
                ]
            )
        return aggregate_fields

    def to_representation(self, instance):
        """Render dimensions first, followed by available generated aggregates."""
        result = OrderedDict()
        for field_name in self.get_fields():
            field_path = self.field_to_database_path(field_name)
            result[field_name] = instance[field_path]
        for field_name in self.get_aggregate_field_names():
            if field_name in instance:
                result[field_name] = instance[field_name]
        return result

    @classmethod
    def get_aggregate_field_name(cls, field_name, aggregate, scope, percentage_of=None):
        """
        Return the generated aggregate output name.

        Aggregate classes include their lowercase aggregate name, for example
        ``amount_sum_row``. Constructed expressions use the supplied key as-is.
        A percentage adds ``_percentage_of_<scope>``, for example
        ``amount_sum_slice_percentage_of_row``.
        """
        assert scope in AggregationScope
        assert percentage_of in AggregationScope or percentage_of is None

        if isclass(aggregate):
            field_name += "_" + aggregate.name.lower()

        field_name += "_" + scope

        if percentage_of:
            field_name += "_percentage_of_" + percentage_of

        return field_name
